# Generated by Django 4.2.6 on 2023-10-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='bounty',
            field=models.ImageField(blank=True, default='blogs/images/Luffy.jpg', upload_to='blogs/images'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='blogs/images/Luffy.jpg', upload_to=''),
        ),
    ]
